name: dockerhub-ci

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    
env:
  tag: $(git rev-parse --short HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build-dockerhub-image
      run: |
        pwd
        ls
        cd ..
        pwd
        ls
        find / | grep Dockerfile
        echo "wtf"        
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t qt-ci .
        docker tag qt-ci:latest ${{ secrets.DOCKER_USER }}/qt-ci:latest
        docker push ${{ secrets.DOCKER_USER }}/qt-ci:latest
